version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@3.0.1

# setup
commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node
    #working_directory: ~/videoapp
    steps:
      - setup
  test:
    docker:
      - image: circleci/ruby:2.7.1-node
      - image: circleci/postgres:11.11
        name: "db"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_HOST_AUTH_METHOD: trust
          PGHOST: "127.0.0.1"
    environment:
      BUNDLE_JOBS: "4"
      BUNDLE_RETRY: "3"
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
    #working_directory: ~/videoapp
    steps:
      - setup
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rspec
          command: bundle exec rspec
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
