default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  passowrd: ""

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
  host: <%= ENV['PGHOST'] || 'db' %>

production:
  <<: *default
  adapter: postgresql
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  database: <%= ENV['MYAPP_DATABASE'] %>
  user:name: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
