default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #####追加#####
  host: db
  username: postgres
  passowrd: ""
  #############

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
  host: "<%= ENV['PGHOST'] || 'db' %>"
production:
  <<: *default
  database: <%= ENV['MYAPP_DATABASE'] %>
  username: <%= ENV['MYAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: <%= ENV['PGHOST'] || 'db' %>
